House price Prediction

In [157]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [158]:
df1=pd.read_csv(r"C:\\Users\\YASHVIR\\Downloads\\archive (10)\\output.csv")
df2=pd.read_csv(r"C:\Users\YASHVIR\Downloads\archive (10)\data.csv")
df1.head()
df2.head()
df=df1.merge(df2,on='price')

In [159]:
(df['sqft_living_x'] == df['sqft_living_y']).value_counts()

False    39756
True      4776
Name: count, dtype: int64

In [160]:
df.shape

(44532, 35)

In [161]:
df.isnull().sum()

date_x             0
price              0
bedrooms_x         0
bathrooms_x        0
sqft_living_x      0
sqft_lot_x         0
floors_x           0
waterfront_x       0
view_x             0
condition_x        0
sqft_above_x       0
sqft_basement_x    0
yr_built_x         0
yr_renovated_x     0
street_x           0
city_x             0
statezip_x         0
country_x          0
date_y             0
bedrooms_y         0
bathrooms_y        0
sqft_living_y      0
sqft_lot_y         0
floors_y           0
waterfront_y       0
view_y             0
condition_y        0
sqft_above_y       0
sqft_basement_y    0
yr_built_y         0
yr_renovated_y     0
street_y           0
city_y             0
statezip_y         0
country_y          0
dtype: int64

In [162]:
df = df.drop(columns=[col for col in df.columns if col.endswith('_y')])
df.columns = df.columns.str.replace('_x', '')

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44532 entries, 0 to 44531
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           44532 non-null  object
 1   price          44532 non-null  float64
 2   bedrooms       44532 non-null  float64
 3   bathrooms      44532 non-null  float64
 4   sqft_living    44532 non-null  int64
 5   sqft_lot       44532 non-null  int64
 6   floors         44532 non-null  float64
 7   waterfront     44532 non-null  int64
 8   view           44532 non-null  int64
 9   condition      44532 non-null  int64
 10  sqft_above     44532 non-null  int64
 11  sqft_basement  44532 non-null  int64
 12  yr_built       44532 non-null  int64
 13  yr_renovated   44532 non-null  int64
 14  street         44532 non-null  object
 15  city           44532 non-null  object
 16  statezip       44532 non-null  object
 17  country        44532 non-null  object
dtypes: float64(4), int64(9), object(5)
memory usage: 6.1+ MB

In [164]:
corr=df.corr(numeric_only=True)['price'].sort_values(ascending=False)
print(corr)

price            1.000000
sqft_living      0.316408
sqft_above       0.274105
bathrooms        0.216049
floors           0.158020
bedrooms         0.120956
sqft_basement    0.119416
view             0.100266
sqft_lot         0.056525
yr_built         0.019374
condition        0.009230
waterfront       0.008667
yr_renovated    -0.021946
Name: price, dtype: float64

In [165]:
df.drop(['date','yr_renovated','waterfront','street'],axis=1,inplace=True)
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,view,condition,sqft_above,sqft_basement,yr_built,city,statezip,country
0,313000.0,3.0,1.5,1340,7912,1.5,0,3,1340,0,1955,Shoreline,WA 98133,USA
1,313000.0,3.0,1.5,1340,7912,1.5,0,3,1340,0,1955,Shoreline,WA 98133,USA
2,313000.0,3.0,1.5,1340,7912,1.5,0,3,1340,0,1955,Shoreline,WA 98133,USA
3,2384000.0,5.0,2.5,3650,9050,2.0,4,5,3370,280,1921,Seattle,WA 98119,USA
4,342000.0,3.0,2.0,1930,11947,1.0,0,4,1930,0,1966,Kent,WA 98042,USA

In [166]:
df.duplicated()

0        False
1         True
2         True
3        False
4        False
         ...
44527    False
44528    False
44529    False
44530    False
44531    False
Length: 44532, dtype: bool

In [167]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44532 entries, 0 to 44531
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          44532 non-null  float64
 1   bedrooms       44532 non-null  float64
 2   bathrooms      44532 non-null  float64
 3   sqft_living    44532 non-null  int64
 4   sqft_lot       44532 non-null  int64
 5   floors         44532 non-null  float64
 6   view           44532 non-null  int64
 7   condition      44532 non-null  int64
 8   sqft_above     44532 non-null  int64
 9   sqft_basement  44532 non-null  int64
 10  yr_built       44532 non-null  int64
 11  city           44532 non-null  object
 12  statezip       44532 non-null  object
 13  country        44532 non-null  object
dtypes: float64(4), int64(7), object(3)
memory usage: 4.8+ MB

In [168]:
df.shape

(44532, 14)

In [169]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['city_x']=le.fit_transform(df['city'])
df['country_x']=le.fit_transform(df["country"])
df["statezip_x"]=le.fit_transform(df["statezip"])


df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,view,condition,sqft_above,sqft_basement,yr_built,city,statezip,country,city_x,country_x,statezip_x
0,313000.0,3.0,1.5,1340,7912,1.5,0,3,1340,0,1955,Shoreline,WA 98133,USA,36,0,62
1,313000.0,3.0,1.5,1340,7912,1.5,0,3,1340,0,1955,Shoreline,WA 98133,USA,36,0,62
2,313000.0,3.0,1.5,1340,7912,1.5,0,3,1340,0,1955,Shoreline,WA 98133,USA,36,0,62
3,2384000.0,5.0,2.5,3650,9050,2.0,4,5,3370,280,1921,Seattle,WA 98119,USA,35,0,58
4,342000.0,3.0,2.0,1930,11947,1.0,0,4,1930,0,1966,Kent,WA 98042,USA,18,0,26

In [170]:
# df=df.drop(['city','country','statezip','street'],axis=1,inplace=True)

In [171]:
from sklearn.model_selection import train_test_split
X=df.drop('price',axis=1)
y=df['price']

In [172]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [173]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

ValueError: could not convert string to float: 'Vashon'

In [174]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

ValueError: could not convert string to float: 'Vashon'

In [ ]:
y_pred_lr = lr.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

print("RMSE:", mean_squared_error(y_test, y_pred_lr))
print("R2 Score:", r2_score(y_test, y_pred_lr))

In [ ]:
from xgboost import XGBRegressor
xg_model=XGBRegressor()

In [ ]:
xg_model.fit(X_train,y_train)
y_pred=xg_model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
print("XGBoost Regressor:")
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf_model=RandomForestRegressor()

rf_model.fit(X_train,y_train)
rf_y_pred=rf_model.predict(X_test_scaled)

In [ ]:
print("Random Forest Regressor:")
print("MSE:", mean_squared_error(y_test, rf_y_pred))
print("R2 Score:", r2_score(y_test, rf_y_pred))

deep learning ANN model

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense ,Dropout

In [ ]:
model=Sequential()
model.add(Dense(64,activation='relu',input_shape=(X_train_scaled.shape[1],)))
model.add(Dropout(0.2))

model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))

model.add(Dense(1))

In [ ]:
model.compile(optimizer='adam',loss='mean_squared_error')

In [ ]:
model.summary()

In [ ]:
y_train_log=np.log1p(y_train)
y_test_log=np.log1p(y_test)

In [ ]:
history=model.fit(X_train_scaled,y_train_log,epochs=100,batch_size=32,validation_split=0.2)

In [ ]:
y_pred_ann=model.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
print("DL RSME:", mean_squared_error(y_test, y_pred_ann))
print("DL R2 Score:",r2_score(y_test, y_pred_ann))

In [ ]:
pd.DataFrame({
    "Model": ["XGBoost Regressor","Random Forest Regressor","Deep Learning Model"],
    "MSE":[mean_squared_error(y_test, y_pred),
           mean_squared_error(y_test , rf_y_pred),
           mean_squared_error(y_test, y_pred_ann)],
    "R2 Score":[r2_score(y_test, y_pred),
                r2_score(y_test, rf_y_pred),
                r2_score(y_test, y_pred_ann)]
})

In [ ]:
import numpy as np
from sklearn.metrics import r2_score

baseline_pred = np.full_like(y_test, np.mean(y_train))
print("Baseline R2:", r2_score(y_test, baseline_pred))